"""Exact-node allowlist for known failures on MetaX MACA."""

_UNSUPPORTED_ARCHITECTURE = "kernel is not supported on the current MACA architecture"
_COMPILATION_FAILURE = "known MACA xcore1000 compilation failure"
_NUMERICAL_MISMATCH = "known MACA numerical mismatch"
_RUNTIME_LAUNCH_ERROR = "known MACA runtime launch error"
_NON_INJECTIVE_LAYOUT = "TileLang rejects the generated loop layout as non-injective"
_CI_EXPECTATION_MISMATCH = "MetaX CI workflow does not match the upstream assertion"
_TRACE_RUNTIME_ERROR = "known MACA trace payload runtime error"


# FIXME(staged-rollout): quarantine the current MetaX backend failures by exact node ID.
#
# Broken invariant: every collected TileOps test passes on the MetaX test runner.
# Why: the backend still has architecture gaps, launch failures, and numerical mismatches.
# Cleanup: remove each entry as soon as its node passes consistently on the MetaX runner.
_MACA_XFAIL_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        _UNSUPPORTED_ARCHITECTURE,
        (
            "tests/ops/attention/test_deepseek_mla_decode.py::test_mla_decode[32-128-1-8192-512-64-dtype0-False]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[causal-fp16-page64]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[noncausal-fp16-page64]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[causal-softcap-fp16-page64]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[causal-bf16-page64]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[causal-fp16-page16]",
            "tests/ops/attention/test_gqa_prefill_paged.py::test_gqa_prefill_paged_with_fp8_kv_cache_fwd[causal-fp16-page128]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-True--1--1-dtype0-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-True--1--1-dtype1-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-True-128--1-dtype2-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-False--1--1-dtype3-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-False-64-64-dtype4-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-128-8-1-128-True-1--1-dtype5-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-False-64-64-dtype6-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-8-64-True--1--1-dtype7-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-16-1-64-True--1--1-dtype8-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-384-8-2-64-True--1--1-dtype9-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-768-8-2-64-False-256--1-dtype10-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[1-2048-8-2-64-True-512--1-dtype11-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-512-8-2-64-False--1-64-dtype12-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::test_gqa_sliding_window_fwd_op[2-256-8-2-64-True-0--1-dtype13-False]",
            "tests/ops/attention/test_gqa_sliding_window.py::TestGroupedQueryAttentionSlidingWindowFwdOpMetrics::test_total_memory_gqa",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q0-seqlens_k0-8-2-64-True--1--1-dtype0-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q1-seqlens_k1-8-2-64-True--1--1-dtype1-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q2-seqlens_k2-8-2-64-True-128--1-dtype2-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q3-seqlens_k3-8-2-64-False--1--1-dtype3-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q4-seqlens_k4-8-2-64-False-64-64-dtype4-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q5-seqlens_k5-8-2-64-True--1--1-dtype5-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q6-seqlens_k6-8-2-64-True-128--1-dtype6-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q7-seqlens_k7-8-2-64-False-64-64-dtype7-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q8-seqlens_k8-8-2-64-False-64-64-dtype8-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q9-seqlens_k9-8-8-64-True--1--1-dtype9-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q10-seqlens_k10-16-1-64-True--1--1-dtype10-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[3-seqlens_q11-seqlens_k11-8-2-64-True--1--1-dtype11-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q12-seqlens_k12-8-2-64-False--1-64-dtype12-False]",
            "tests/ops/attention/test_gqa_sliding_window_varlen.py::test_gqa_sliding_window_varlen_fwd_op[2-seqlens_q13-seqlens_k13-8-2-64-True-0--1-dtype13-False]",
            "tests/ops/attention/test_mha.py::test_mha_bwd[full-bwd-fp16-large]",
            "tests/ops/attention/test_mha.py::test_mha_bwd[full-bwd-bf16-tuned]",
            "tests/ops/test_kernel_selection.py::test_paged_prefill_fp8_cache_dispatch_is_unchanged",
        ),
    ),
    (
        _COMPILATION_FAILURE,
        (
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[2-64-2-64-64-32-dtype0-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[2-64-2-64-64-32-dtype1-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[2-64-2-64-64-32-dtype2-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[2-64-2-64-64-32-dtype0-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[2-64-2-64-64-32-dtype1-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[2-64-2-64-64-32-dtype2-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[2-64-2-64-64-32-dtype0-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[2-64-2-64-64-32-dtype1-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[2-64-2-64-64-32-dtype2-False]",
            "tests/ops/test_gated_deltanet_prefill.py::test_gated_deltanet_prefill_fwd[1-64-2-64-64-32-dtype0-False]",
            "tests/ops/test_gla_chunkwise_fwd.py::test_gla_fwd[2-64-2-64-64-64-dtype0-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[1-128-4-64-64-32-dtype3-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[1-128-4-64-64-32-dtype4-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[1-128-4-64-64-32-dtype5-False]",
            "tests/ops/test_deltanet_chunkwise_bwd.py::test_deltanet_bwd[full-bf16-tuned]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[1-128-4-64-64-32-dtype3-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[1-128-4-64-64-32-dtype4-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[1-128-4-64-64-32-dtype5-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[2-8192-4-64-64-64-dtype6-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[2-16384-4-64-64-64-dtype7-False]",
            "tests/ops/test_deltanet_fwd.py::test_deltanet_fwd[full-bf16-tuned]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[1-128-4-64-64-32-dtype3-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[1-128-4-64-64-32-dtype4-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[1-128-4-64-64-32-dtype5-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[2-8192-4-64-64-64-dtype6-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[2-16384-4-64-64-64-dtype7-False]",
            "tests/ops/test_gated_deltanet_fwd.py::test_gated_deltanet_fwd[full-bf16-tuned]",
            "tests/ops/test_gla_chunkwise_fwd.py::test_gla_fwd[1-128-4-64-64-64-dtype3-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[1-16-8-512-128-128-dtype0-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[2-8-4-1024-64-256-dtype1-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[1-32-8-256-128-64-dtype2-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[1-8-4-1024-64-256-dtype3-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[2-16-8-512-128-128-dtype4-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[1-16-4-2048-128-512-dtype5-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op[1-32-16-512-64-128-dtype6-False]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_non_divisible_128_page_split",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op_softmax_controls[custom-sm-scale]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_op_softmax_controls[softcap]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_kernel_handles_natural_unaligned_shape[dtype0]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_kernel_handles_natural_unaligned_shape[dtype1]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_kernel_handles_natural_unaligned_shape[dtype2]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_async_copy_handles_row_tail",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_async_policy_edge_correctness[fp16-lower-inside]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_op[1024-3000-dtype6]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_op[1024-3000-dtype7]",
            "tests/ops/test_ada_layer_norm.py::test_ada_layer_norm_op[1024-3000-dtype8]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_kernel_handles_natural_unaligned_shape[dtype0]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_kernel_handles_natural_unaligned_shape[dtype1]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_kernel_handles_natural_unaligned_shape[dtype2]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_async_copy_handles_row_tail",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_op[1024-3000-dtype6]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_op[1024-3000-dtype7]",
            "tests/ops/test_ada_layer_norm_zero.py::test_ada_layer_norm_zero_op[1024-3000-dtype8]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd_segmented_carry_matches_sequential_d128[dtype0-64]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd_segmented_carry_matches_sequential_d128[dtype1-128]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[1-128-2-128-128-64-dtype6-False]",
            "tests/ops/test_multi_dtype_instance.py::test_bitwise_alternates_between_bool_and_integer_storage",
            "tests/ops/test_multi_dtype_instance.py::test_logical_and_output_stays_bool_across_input_storage",
            "tests/ops/test_multi_dtype_instance.py::test_single_tensor_op_records_its_dtype[LogicalNotFwdOp]",
        ),
    ),
    (
        _NUMERICAL_MISMATCH,
        (
            "tests/ops/test_fused_moe_experts.py::TestFusedMoEExpertsNopadPersistent3WGFwdOp::test_forward_matches_torch_ref_activation[float16-gelu_and_mul]",
            "tests/kernels/test_linear_attn_autotune.py::test_default_config_width_is_one_the_kernel_builds[DeltaNetFwdKernel]",
            "tests/kernels/test_linear_attn_autotune.py::test_default_config_width_is_one_the_kernel_builds[GatedDeltaNetFwdKernel]",
            "tests/ops/test_argreduce.py::test_argreduce_large_n[argmax-dtype0]",
            "tests/ops/test_argreduce.py::test_argreduce_large_n[argmin-dtype1]",
            "tests/ops/test_argreduce.py::test_argreduce_first_index_and_nan_semantics[argmax]",
            "tests/ops/test_argreduce.py::test_argreduce_first_index_and_nan_semantics[argmin]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[8-argmax]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[8-argmin]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[4096-argmax]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[4096-argmin]",
            "tests/ops/test_argreduce.py::test_argreduce_strided_axis_crossover[shape1-1-False]",
            "tests/ops/test_argreduce.py::test_argmax_op[128-300-dtype5]",
            "tests/ops/test_argreduce.py::test_argmax_op[128-300-dtype6]",
            "tests/ops/test_argreduce.py::test_argmax_spec_dim[shape4-1-False-dtype4]",
            "tests/ops/test_argreduce.py::test_argmin_op[128-300-dtype5]",
            "tests/ops/test_argreduce.py::test_argmin_op[128-300-dtype6]",
            "tests/ops/test_argreduce.py::test_argmin_spec_dim[shape4-1-False-dtype4]",
            "tests/ops/test_argreduce.py::test_argmax_dim_none[shape6-dtype6]",
            "tests/ops/test_argreduce.py::test_argmin_dim_none[shape6-dtype6]",
        ),
    ),
    (
        _RUNTIME_LAUNCH_ERROR,
        (
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[2-64-2-64-64-32-dtype0-False]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[2-64-2-64-64-32-dtype1-False]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[2-64-2-64-64-32-dtype2-False]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[1-128-4-64-64-32-dtype3-False]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[1-128-4-64-64-32-dtype4-False]",
            "tests/ops/test_gated_deltanet_chunkwise_bwd.py::test_gated_deltanet_bwd[1-128-4-64-64-32-dtype5-False]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[40960-argmax]",
            "tests/ops/test_argreduce.py::test_argreduce_ties_between_two_nans[40960-argmin]",
            "tests/ops/test_reduce.py::test_reduce_caller_tile_n_validated",
            "tests/ops/test_reduce.py::test_reduce_tiled_autotune[sum]",
        ),
    ),
    (
        _NON_INJECTIVE_LAYOUT,
        (
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[2-64-2-64-64-64-dtype0-False]",
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[2-64-2-64-64-64-dtype1-False]",
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[2-64-2-64-64-64-dtype2-False]",
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[1-128-4-64-64-64-dtype3-False]",
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[1-128-4-64-64-64-dtype4-False]",
            "tests/ops/test_gla_chunkwise_bwd.py::test_gla_bwd[1-128-4-64-64-64-dtype5-False]",
        ),
    ),
    (
        _CI_EXPECTATION_MISMATCH,
        (
            "tests/ops/attention/test_gqa_decode.py::test_gqa_decode_bs1_dispatch",
            "tests/ops/attention/test_gqa_decode.py::test_gqa_decode_bs1_runtime_context_switch",
            "tests/ops/attention/test_gqa_decode.py::test_gqa_decode_bs1_group4",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_bs1_fixed_tier_correctness[no-split]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_bs1_fixed_tier_correctness[ctx-reversed-pages]",
            "tests/ops/attention/test_gqa_decode_paged.py::test_gqa_decode_paged_bs1_dispatch",
            "tests/ops/attention/test_gqa_fp8.py::test_gqa_prefill_fp8_tensor_core_rejects_unaligned_q_tiles[224]",
            "tests/ops/attention/test_gqa_fp8.py::test_gqa_prefill_fp8_tensor_core_rejects_unaligned_q_tiles[672]",
            "tests/ops/test_deltanet_recurrence.py::test_deltanet_decode_raw_cuda_config_requires_full_warp_mapping",
            "tests/ops/test_deltanet_recurrence.py::test_deltanet_decode_raw_cuda_config_requires_two_lane_group",
            "tests/ops/test_family_dispatch.py::test_gemm_is_refused_where_neither_implementation_runs",
            "tests/ops/test_fused_moe_experts.py::test_use_fused_activation_refuses_a_conflicting_gemm_override",
            "tests/ops/test_gated_deltanet_recurrence.py::test_gated_deltanet_decode_raw_cuda_config_requires_full_warp_mapping",
            "tests/ops/test_gated_deltanet_recurrence.py::test_gated_deltanet_decode_raw_cuda_config_requires_two_lane_group",
            "tests/ops/test_kernel_selection.py::test_decode_dispatch_is_unchanged[bs1-fp16]",
            "tests/ops/test_kernel_selection.py::test_paged_decode_dispatch_is_unchanged[bs1-fp16]",
            "tests/ops/test_multi_dtype_instance.py::test_attention_decode_reselects_the_kernel_per_dtype",
            "tests/ops/test_multi_dtype_instance.py::test_attention_square_prefill_reselects_the_kernel_per_dtype",
        ),
    ),
    (
        _TRACE_RUNTIME_ERROR,
        (
            "tests/trace/test_payload.py::test_payload_with_range_start_end",
            "tests/trace/test_payload.py::test_implicit_thread_blocks_with_payload_e2e",
        ),
    ),
)

MACA_XFAILS = {
    nodeid: reason
    for reason, nodeids in _MACA_XFAIL_GROUPS
    for nodeid in nodeids
}

if len(MACA_XFAILS) != sum(len(nodeids) for _, nodeids in _MACA_XFAIL_GROUPS):
    raise ValueError("duplicate node ID in the MACA xfail allowlist")
